#!/usr/bin/env python3
"""
Generate Coral source spec YAMLs for Helmsman's Demo Mode.

Each source is `backend: file`, reads JSONL from ./data/<source>/, and exposes
schemas named `<source>_demo` (e.g. github_demo) so they don't collide with
the bundled live sources.

Output: ./coral-sources/*.yaml
Run:    python3 scripts/generate_source_specs.py
"""
from __future__ import annotations

from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "coral-sources"

# file:// URIs must URL-encode reserved characters (e.g. spaces).
DATA_URI = "file://" + quote(DATA.as_posix(), safe="/") + "/"

UTF8 = "Utf8"
INT = "Int64"
FLOAT = "Float64"
BOOL = "Boolean"
TS = "Timestamp"
JSON = "Json"


def render_table(name: str, description: str, sub_dir: str,
                 columns: list[tuple[str, str]], file_name: str | None = None) -> str:
    # Each table is pinned to its own JSONL file so a directory full of
    # tables doesn't cross-pollute schemas.
    fname = file_name or f"{name}.jsonl"
    lines = [
        f"  - name: {name}",
        f"    description: {description}",
        f"    format: jsonl",
        f"    source:",
        f"      location: {DATA_URI}{sub_dir}/",
        f'      glob: "{fname}"',
        f"    columns:",
    ]
    for col, typ in columns:
        lines.append(f"      - name: {col}")
        lines.append(f"        type: {typ}")
    return "\n".join(lines)


def render_source(schema: str, version: str, description: str,
                  test_queries: list[str], tables: list[str]) -> str:
    lines = [
        f"# Auto-generated by scripts/generate_source_specs.py",
        f"# Demo source for Helmsman -- backed by local JSONL under ./data/{schema.replace('_demo','')}/",
        f"name: {schema}",
        f"version: {version}",
        f"dsl_version: 3",
        f"backend: file",
        f"description: |",
        f"  {description}",
        f"test_queries:",
    ]
    for q in test_queries:
        # quote with single quotes; escape any single-quote in q
        safe = q.replace("'", "''")
        lines.append(f"  - '{safe}'")
    lines.append("tables:")
    for t in tables:
        lines.append(t)
    return "\n".join(lines) + "\n"


GITHUB_DEMO = render_source(
    schema="github_demo",
    version="0.1.0",
    description="Helmsman demo GitHub source -- JSONL-backed mirror of the bundled github schema.",
    test_queries=[
        "SELECT * FROM github_demo.pulls LIMIT 1",
        "SELECT * FROM github_demo.reviews LIMIT 1",
        "SELECT * FROM github_demo.issues LIMIT 1",
    ],
    tables=[
        render_table(
            "pulls", "Pull requests across all repos", "github",
            [
                ("number", INT), ("owner", UTF8), ("repo", UTF8), ("title", UTF8),
                ("state", UTF8),
                ("user__login", UTF8), ("user__name", UTF8),
                ("html_url", UTF8),
                ("created_at", UTF8), ("updated_at", UTF8),
                ("merged_at", UTF8), ("closed_at", UTF8),
                ("base_ref", UTF8), ("head_ref", UTF8),
                ("additions", INT), ("deletions", INT), ("changed_files", INT),
                ("body", UTF8),
                ("labels", JSON), ("requested_reviewers", JSON),
                ("review_decision", UTF8),
            ],
        ),
        render_table(
            "reviews", "Pull request reviews", "github",
            [
                ("id", INT), ("owner", UTF8), ("repo", UTF8), ("pull_number", INT),
                ("user__login", UTF8), ("user__name", UTF8),
                ("state", UTF8), ("submitted_at", UTF8), ("body", UTF8),
            ],
        ),
        render_table(
            "pull_reviewers",
            "Normalized many-to-many of pulls and requested reviewers",
            "github",
            [
                ("owner", UTF8), ("repo", UTF8), ("pull_number", INT),
                ("reviewer_login", UTF8), ("reviewer_name", UTF8),
                ("pull_state", UTF8),
                ("pull_created_at", UTF8), ("pull_updated_at", UTF8),
            ],
        ),
        render_table(
            "issues", "Repository issues", "github",
            [
                ("number", INT), ("owner", UTF8), ("repo", UTF8), ("title", UTF8),
                ("state", UTF8),
                ("user__login", UTF8), ("user__name", UTF8),
                ("assignee__login", UTF8),
                ("html_url", UTF8),
                ("created_at", UTF8), ("updated_at", UTF8),
                ("labels", JSON), ("body", UTF8),
            ],
        ),
        render_table(
            "commits", "Commits on main", "github",
            [
                ("sha", UTF8), ("owner", UTF8), ("repo", UTF8),
                ("author__login", UTF8), ("author__name", UTF8),
                ("committed_at", UTF8), ("message", UTF8), ("pull_number", INT),
            ],
        ),
        render_table(
            "repos", "Repositories", "github",
            [
                ("owner", UTF8), ("name", UTF8), ("full_name", UTF8),
                ("description", UTF8), ("default_branch", UTF8),
                ("private", BOOL), ("language", UTF8),
                ("stargazers_count", INT), ("forks_count", INT), ("open_issues_count", INT),
                ("pushed_at", UTF8),
            ],
        ),
    ],
)


LINEAR_DEMO = render_source(
    schema="linear_demo",
    version="0.1.0",
    description="Helmsman demo Linear source -- JSONL mirror of the bundled linear schema.",
    test_queries=[
        "SELECT * FROM linear_demo.issues LIMIT 1",
        "SELECT * FROM linear_demo.attachments LIMIT 1",
    ],
    tables=[
        render_table(
            "issues", "Linear issues across cycles", "linear",
            [
                ("id", UTF8), ("identifier", UTF8), ("team_key", UTF8),
                ("title", UTF8),
                ("state__name", UTF8), ("state__type", UTF8),
                ("priority", INT), ("priority_label", UTF8),
                ("assignee__email", UTF8), ("assignee__name", UTF8),
                ("creator__email", UTF8), ("creator__name", UTF8),
                ("created_at", UTF8), ("updated_at", UTF8),
                ("completed_at", UTF8), ("due_date", UTF8),
                ("cycle__name", UTF8),
                ("url", UTF8), ("description", UTF8),
            ],
        ),
        render_table(
            "attachments", "Links between Linear issues and external URLs", "linear",
            [
                ("id", UTF8), ("issue_id", UTF8), ("issue_identifier", UTF8),
                ("title", UTF8), ("url", UTF8), ("created_at", UTF8),
            ],
        ),
        render_table(
            "cycles", "Linear cycles", "linear",
            [
                ("id", UTF8), ("name", UTF8), ("starts_at", UTF8),
                ("ends_at", UTF8), ("team_key", UTF8), ("progress", FLOAT),
            ],
        ),
    ],
)


SLACK_DEMO = render_source(
    schema="slack_demo",
    version="0.1.0",
    description="Helmsman demo Slack source -- JSONL mirror of the bundled slack schema.",
    test_queries=[
        "SELECT * FROM slack_demo.messages LIMIT 1",
        "SELECT * FROM slack_demo.channels LIMIT 1",
    ],
    tables=[
        render_table(
            "messages", "Channel and thread messages", "slack",
            [
                ("id", UTF8),
                ("channel_id", UTF8), ("channel_name", UTF8),
                ("user__login", UTF8), ("user__name", UTF8),
                ("ts", UTF8), ("iso_ts", UTF8),
                ("text", UTF8), ("thread_ts", UTF8),
                ("mentions", JSON),
            ],
        ),
        render_table(
            "channels", "Slack channels", "slack",
            [
                ("id", UTF8), ("name", UTF8),
                ("is_private", BOOL), ("topic", UTF8),
            ],
        ),
        render_table(
            "message_mentions",
            "Normalized one-row-per-mention table for Slack messages",
            "slack",
            [
                ("message_id", UTF8), ("channel_id", UTF8), ("channel_name", UTF8),
                ("iso_ts", UTF8),
                ("mentioned_login", UTF8), ("mentioned_name", UTF8),
                ("author_login", UTF8), ("text", UTF8),
            ],
        ),
    ],
)


SENTRY_DEMO = render_source(
    schema="sentry_demo",
    version="0.1.0",
    description="Helmsman demo Sentry source -- JSONL mirror of the bundled sentry schema.",
    test_queries=[
        "SELECT * FROM sentry_demo.issues LIMIT 1",
    ],
    tables=[
        render_table(
            "issues", "Sentry issues across projects", "sentry",
            [
                ("id", UTF8), ("short_id", UTF8),
                ("title", UTF8), ("culprit", UTF8),
                ("level", UTF8), ("status", UTF8),
                ("first_seen", UTF8), ("last_seen", UTF8),
                ("count", INT), ("user_count", INT),
                ("project_slug", UTF8), ("permalink", UTF8),
                ("release", UTF8),
                ("tags__pr", UTF8), ("tags__route", UTF8),
                ("stack_top", UTF8),
            ],
        ),
    ],
)


DATADOG_DEMO = render_source(
    schema="datadog_demo",
    version="0.1.0",
    description="Helmsman demo Datadog source -- JSONL mirror of the bundled datadog schema.",
    test_queries=[
        "SELECT * FROM datadog_demo.metrics LIMIT 1",
        "SELECT * FROM datadog_demo.monitors LIMIT 1",
    ],
    tables=[
        render_table(
            "metrics", "Sampled metric points", "datadog",
            [
                ("metric", UTF8), ("service", UTF8), ("route", UTF8),
                ("value_pct", FLOAT), ("timestamp", UTF8),
            ],
        ),
        render_table(
            "monitors", "Monitors and their current statuses", "datadog",
            [
                ("id", INT), ("name", UTF8), ("status", UTF8),
                ("service", UTF8), ("query", UTF8),
                ("tags", JSON), ("modified_at", UTF8),
            ],
        ),
    ],
)


CALENDAR_DEMO = render_source(
    schema="calendar_demo",
    version="0.1.0",
    description="Helmsman demo Google Calendar source -- JSONL mirror of the bundled google_calendar schema.",
    test_queries=[
        "SELECT * FROM calendar_demo.events LIMIT 1",
    ],
    tables=[
        render_table(
            "events", "Calendar events", "calendar",
            [
                ("id", UTF8), ("summary", UTF8),
                ("start_at", UTF8), ("end_at", UTF8),
                ("attendees", JSON), ("organizer", UTF8),
                ("location", UTF8), ("description", UTF8),
            ],
        ),
        render_table(
            "event_attendees",
            "Normalized one-row-per-attendee table for calendar events",
            "calendar",
            [
                ("event_id", UTF8), ("summary", UTF8),
                ("start_at", UTF8), ("end_at", UTF8),
                ("attendee_login", UTF8), ("attendee_name", UTF8),
                ("organizer", UTF8),
            ],
        ),
    ],
)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, body in [
        ("github_demo.yaml",   GITHUB_DEMO),
        ("linear_demo.yaml",   LINEAR_DEMO),
        ("slack_demo.yaml",    SLACK_DEMO),
        ("sentry_demo.yaml",   SENTRY_DEMO),
        ("datadog_demo.yaml",  DATADOG_DEMO),
        ("calendar_demo.yaml", CALENDAR_DEMO),
    ]:
        (OUT / name).write_text(body, encoding="utf-8")
        print(f"  wrote {(OUT / name).relative_to(ROOT)}")
    print(f"Done. Data URI base: {DATA_URI}")


if __name__ == "__main__":
    main()
